import Head from "next/head";
import Nav from "./Nav";
import Footer from "./Footer";
import styled from "styled-components";

const Layout = ({ children }) => {
  return (
    <StyledLayout>
      <Head>
        <title>코로나 선별진료소</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="bodyContainer">
        <Nav />
        <div className="container">{children}</div>
      </div>
      <Footer />
    </StyledLayout>
  );
};

const StyledLayout = styled.div`
  .bodyContainer {
    min-height: 100vh;
    height: 100%;
    background-color: #fff8f8;
    position: relative;
    padding-bottom: 25rem;
  }

  //! max-width 체크
  .container {
    max-width: 1400px;
    margin: 0 auto;
    text-align: center;
  }
`;

export default Layout;
